// <auto-generated />
using System;
using LMSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMSystem.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260727103338_UpdateSeedDataNames")]
    partial class UpdateSeedDataNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LMSystem.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("Books13");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Sunil Kumar and Rajesh Tiwari",
                            ISBN = "978-0201616224",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Sanjay Mishra",
                            ISBN = "978-0132350884",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Design Pattern using C#"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Pranaya Kumar Rout",
                            ISBN = "978-0451616235",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2022, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mastering ASP.NET Core"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Rakesh Kumat",
                            ISBN = "978-4562350123",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "SQL Server with DBA"
                        });
                });

            modelBuilder.Entity("LMSystem.Models.BorrowRecord", b =>
                {
                    b.Property<int>("BorrowRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("BorrowRecordId");

                    b.HasIndex("BookId");

                    b.ToTable("BorrowRecords13");
                });

            modelBuilder.Entity("LMSystem.Models.LibrarianModel", b =>
                {
                    b.Property<int>("LibrarianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("LibrarianId");

                    b.ToTable("Librarians");

                    b.HasData(
                        new
                        {
                            LibrarianId = 1,
                            Age = 34,
                            Name = "Priya Sharma",
                            Phone = "555-0201"
                        },
                        new
                        {
                            LibrarianId = 2,
                            Age = 28,
                            Name = "Rahul Verma",
                            Phone = "555-0202"
                        },
                        new
                        {
                            LibrarianId = 3,
                            Age = 45,
                            Name = "Amit Patel",
                            Phone = "555-0203"
                        },
                        new
                        {
                            LibrarianId = 4,
                            Age = 39,
                            Name = "Neha Gupta",
                            Phone = "555-0204"
                        },
                        new
                        {
                            LibrarianId = 5,
                            Age = 40,
                            Name = "Vikram Singh",
                            Phone = "555-0205"
                        });
                });

            modelBuilder.Entity("LMSystem.Models.LoginModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("logintab");

                    b.HasData(
                        new
                        {
                            id = 1,
                            password = "12345",
                            username = "admin"
                        },
                        new
                        {
                            id = 2,
                            password = "myc546",
                            username = "mycodingproject"
                        },
                        new
                        {
                            id = 3,
                            password = "myc",
                            username = "my"
                        });
                });

            modelBuilder.Entity("LMSystem.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Publications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Global Media Group",
                            Title = "The Daily Times",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "WallSt Press",
                            Title = "Financial Chronicle",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Silicon Valley Pubs",
                            Title = "Tech Weekly News",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "City Press House",
                            Title = "Metro Morning Post",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = false,
                            PublishedDate = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Global Media Group",
                            Title = "Saturday Sports Herald",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "NatGeo Society",
                            Title = "National Geographic Vol 45",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Condé Nast",
                            Title = "Vogue Fashion Summer",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            IsAvailable = false,
                            PublishedDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Forbes Media",
                            Title = "Forbes Business 30 Under 30",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Future US",
                            Title = "PC Gamer Ultimate",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Springer Nature",
                            Title = "Scientific American",
                            Type = 1
                        });
                });

            modelBuilder.Entity("LMSystem.Models.StudentModel", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "ananya.i@email.com",
                            Phone = "555-0101",
                            StudentName = "Ananya Iyer"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "rohan.k@email.com",
                            Phone = "555-0102",
                            StudentName = "Rohan Kapoor"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "arjun.d@email.com",
                            Phone = "555-0103",
                            StudentName = "Arjun Das"
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "divya.r@email.com",
                            Phone = "555-0104",
                            StudentName = "Divya Rao"
                        },
                        new
                        {
                            StudentId = 5,
                            Email = "aditya.j@email.com",
                            Phone = "555-0105",
                            StudentName = "Aditya Joshi"
                        });
                });

            modelBuilder.Entity("LMSystem.Models.BorrowRecord", b =>
                {
                    b.HasOne("LMSystem.Models.Book", "Book")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LMSystem.Models.Book", b =>
                {
                    b.Navigation("BorrowRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
